name: Build
on:
  push:
    branches: main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PASSWORD }}

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: "Set up Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: "pyproject.toml"

      - name: Build Python wheel
        run: |
          uv build --wheel
          uv export --frozen --no-dev --no-hashes --no-emit-project > dist/requirements.txt

      - uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build node modules and JS bundle
        run: npm install && npm run build

      - name: Build and load into Docker
        id: docker_build
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          load: true
          context: dist
          file: Dockerfile
          tags: ghcr.io/majsvaffla/ärdetdags:${{ github.sha }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Test that the image basically works
        run: docker run --rm ghcr.io/majsvaffla/ärdetdags:${{ github.sha }} python -c "import ärdetdags"

      - name: Push to container registry
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64
          push: true
          context: dist
          file: Dockerfile
          tags: ghcr.io/majsvaffla/ärdetdags:${{ github.sha }},ghcr.io/majsvaffla/ärdetdags:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
