name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches: ["*"]
  workflow_run:
    workflows: ["Build"]
    types:
      - completed
jobs:
  linting:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/majsvaffla/dax:${{ github.sha }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PASSWORD }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: ruff check
        run: ruff check

      - name: ruff format
        run: ruff format --check

  testing:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/majsvaffla/dax:${{ github.sha }}
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PASSWORD }}
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2

      - name: pytest
        run: pytest
